In [56]:
import pandas as pd
df = pd.read_csv("Final_data.csv")
movie_data = pd.read_csv("/title_basics/data.tsv",sep='\t')

FileNotFoundError: [Errno 2] File /title_basics/data.tsv does not exist: '/title_basics/data.tsv'

In [54]:
df

,tconst,actor,actress,archive_footage,archive_sound,cinematographer,composer,director,editor,producer,...,self,writer,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,world_revenue,averageRating,numVotes
0,tt0010180,NaN,NaN,NaN,NaN,NaN,NaN,nm0895048,NaN,nm13054604,...,"nm0449292,nm0501924,nm0873654",NaN,Godovshchina revolyutsii,Godovshchina revolyutsii,1918,119,Documentary,9685.0,6.8,112
1,tt0010323,"nm0470328,nm0891998,nm0270415",nm0196820,NaN,NaN,NaN,"nm0110640,nm0031350,nm0005959",nm0927468,NaN,NaN,...,NaN,"nm0562346,nm0417917",The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,1920,76,"Horror,Mystery,Thriller",8811.0,8.0,62554
2,tt0011440,"nm0073680,nm0753185,nm0814027","nm0526192,nm0923198,nm0814028,nm0084841",NaN,NaN,nm0774256,nm0357165,NaN,NaN,NaN,...,NaN,nm0359105,Markens grøde,Markens grøde,1921,107,Drama,4272.0,6.5,236
3,tt0012190,"nm0884388,nm0134251,nm0842522",nm0855935,NaN,NaN,NaN,nm0002301,nm0002271,NaN,"nm0002206,nm0318647",...,NaN,"nm0087658,nm0558923",The Four Horsemen of the Apocalypse,The Four Horsemen of the Apocalypse,1921,150,"Drama,Romance,War",9183673.0,7.2,3342
4,tt0012349,"nm0088471,nm0000122,nm0001067,nm0588033,nm0042...","nm0701012,nm0047800,nm0048798",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,The Kid,The Kid,1921,68,"Comedy,Drama,Family",41960.0,8.3,124464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43912,tt9914286,"nm1832009,nm2456249,nm10569025",nm7659571,NaN,NaN,"nm6314548,nm2548836",nm8744743,NaN,NaN,nm10569206,...,NaN,nm1902682,Sokagin Çocuklari,Sokagin Çocuklari,2019,98,"Drama,Family",2833.0,4.5,218
43913,tt9914942,"nm10823679,nm1290838,nm5580678",nm10814833,NaN,NaN,nm1966322,nm2262072,nm1716653,nm0739828,NaN,...,NaN,"nm3678448,nm9361716",Life Without Sara Amat,La vida sense la Sara Amat,2019,74,Drama,59794.0,6.7,147
43914,tt9914972,NaN,NaN,NaN,NaN,nm0569845,nm4407607,"nm5293094,nm0743916",NaN,NaN,...,NaN,"nm5292318,nm6760227",Blind Ambition,Blind Ambition,2021,96,Documentary,124317.0,7.8,47
43915,tt9915872,NaN,"nm0755725,nm4392634",NaN,NaN,NaN,NaN,nm8063415,NaN,NaN,...,NaN,nm2507310,The Last White Witch,My Girlfriend is a Wizard,2019,97,"Comedy,Drama,Fantasy",4540085.0,6.9,8
43916,tt9916362,"nm0107165,nm0266723","nm3766704,nm10678594",NaN,NaN,NaN,nm5813626,nm1893148,NaN,"nm2970042,nm4065853,nm1086949",...,NaN,nm3471432,Coven,Akelarre,2020,92,"Drama,History",317907.0,6.4,4632

In [10]:
df = df[['tconst','writer','director','startYear','runtimeMinutes','genres','world_revenue','averageRating','numVotes']]

In [50]:
def get_name(row):
    print('here')
    writers = row.writer.split(',')
    directors = row.director.split(',')
    print(writers)
    for i in range(len(writers)):
        writers[i] = names[names.nconst == writers[i]].primaryName.to_list()[0]
    for i in range(len(directors)):
        directors[i] = names[names.nconst == directors[i]].primaryName.to_list()[0]
    print(directors)
    row.writer = ','.join(writers)
    row.director= ','.join(directors)
    print(row)
    return row

In [45]:
df[df['tconst'] == 'tt4154796'].writer.to_list()

['nm0456158,nm1321655,nm1321656,nm0498278']

,tconst,writer,director,startYear,runtimeMinutes,genres,world_revenue,averageRating,numVotes
33771,tt4154796,"nm0456158,nm1321655,nm1321656,nm0498278","nm0751577,nm0751648",2019,181,"Action,Adventure,Drama",2.797501e+09,8.4,1049353

here
['nm0456158', 'nm1321655', 'nm1321656', 'nm0498278']
['Anthony Russo', 'Joe Russo']
tconst                                                    tt4154796
writer            Jack Kirby,Christopher Markus,Stephen McFeely,...
director                                    Anthony Russo,Joe Russo
startYear                                                      2019
runtimeMinutes                                                  181
genres                                       Action,Adventure,Drama
world_revenue                                            2.7975e+09
averageRating                                                   8.4
numVotes                                                    1049353
Name: 33771, dtype: object
here
['Jack Kirby', 'Christopher Markus', 'Stephen McFeely', 'Stan Lee']

IndexError: list index out of range

In [6]:
names = pd.read_csv('data.tsv',sep='\t')

In [7]:
names

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0031983,tt0072308,tt0050419,tt0053137"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0038355,tt0037382,tt0071877"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0056404,tt0049189,tt0054452,tt0057345"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0080455,tt0078723,tt0072562,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0060827,tt0050976,tt0083922"
...,...,...,...,...,...,...
11622819,nm9993714,Romeo del Rosario,\N,\N,"animation_department,art_department","tt14069590,tt2455546,tt11657662"
11622820,nm9993716,Essias Loberg,\N,\N,NaN,\N
11622821,nm9993717,Harikrishnan Rajan,\N,\N,cinematographer,tt8736744
11622822,nm9993718,Aayush Nair,\N,\N,cinematographer,\N
11622823,nm9993719,Andre Hill,\N,\N,NaN,\N

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43917 entries, 0 to 43916
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   writer          29516 non-null  object
 1   director        41862 non-null  object
 2   startYear       43917 non-null  int64
 3   runtimeMinutes  43917 non-null  int64
 4   genres          43917 non-null  object
 5   world_revenue   43917 non-null  float64
 6   averageRating   43917 non-null  float64
 7   numVotes        43917 non-null  int64
dtypes: float64(2), int64(3), object(3)
memory usage: 2.7+ MB

In [14]:
df.shape

(43917, 6)

In [15]:
df.genres  = df.genres.apply(lambda x: x.split(",")[0])

In [16]:
df

,startYear,runtimeMinutes,genres,world_revenue,averageRating,numVotes
0,1918,119,Documentary,9685.0,6.8,112
1,1920,76,Horror,8811.0,8.0,62554
2,1921,107,Drama,4272.0,6.5,236
3,1921,150,Drama,9183673.0,7.2,3342
4,1921,68,Comedy,41960.0,8.3,124464
...,...,...,...,...,...,...
43912,2019,98,Drama,2833.0,4.5,218
43913,2019,74,Drama,59794.0,6.7,147
43914,2021,96,Documentary,124317.0,7.8,47
43915,2019,97,Comedy,4540085.0,6.9,8
43916,2020,92,Drama,317907.0,6.4,4632

> __Vectorize__

In [17]:
df = pd.get_dummies(df,prefix=['genres'], columns = ['genres'], drop_first=True)

In [18]:
df

,startYear,runtimeMinutes,world_revenue,averageRating,numVotes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,...,genres_Horror,genres_Music,genres_Musical,genres_Mystery,genres_Romance,genres_Sci-Fi,genres_Sport,genres_Thriller,genres_War,genres_Western
0,1918,119,9685.0,6.8,112,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1920,76,8811.0,8.0,62554,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1921,107,4272.0,6.5,236,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1921,150,9183673.0,7.2,3342,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1921,68,41960.0,8.3,124464,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43912,2019,98,2833.0,4.5,218,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43913,2019,74,59794.0,6.7,147,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43914,2021,96,124317.0,7.8,47,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43915,2019,97,4540085.0,6.9,8,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
43916,2020,92,317907.0,6.4,4632,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df.describe()

,startYear,runtimeMinutes,world_revenue,averageRating,numVotes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,...,genres_Horror,genres_Music,genres_Musical,genres_Mystery,genres_Romance,genres_Sci-Fi,genres_Sport,genres_Thriller,genres_War,genres_Western
count,43917.000000,43917.000000,4.391700e+04,43917.000000,4.391700e+04,43917.000000,43917.000000,43917.00000,43917.000000,43917.000000,...,43917.000000,43917.000000,43917.000000,43917.000000,43917.000000,43917.000000,43917.000000,43917.000000,43917.000000,43917.000000
mean,2008.361705,103.000615,1.672718e+07,6.128549,1.992084e+04,0.052941,0.016395,0.04743,0.281235,0.051620,...,0.033654,0.001116,0.001639,0.003666,0.006490,0.001161,0.000364,0.008903,0.000250,0.000478
std,11.907080,21.490456,7.664132e+07,1.143335,8.295234e+04,0.223918,0.126989,0.21256,0.449607,0.221261,...,0.180340,0.033384,0.040457,0.060437,0.080297,0.034058,0.019084,0.093937,0.015825,0.021862
min,1918.000000,44.000000,1.000000e+00,1.000000,5.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2005.000000,90.000000,4.356400e+04,5.500000,2.180000e+02,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2011.000000,99.000000,4.695710e+05,6.300000,9.910000e+02,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2016.000000,111.000000,4.387907e+06,6.900000,6.017000e+03,0.000000,0.000000,0.00000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2022.000000,999.000000,2.847380e+09,9.700000,2.584626e+06,1.000000,1.000000,1.00000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [20]:
df = df[df.runtimeMinutes < 300]

In [21]:
df = df[df.startYear > 2000]

In [22]:
df = df[df.world_revenue > 1e4]

In [23]:
df

,startYear,runtimeMinutes,world_revenue,averageRating,numVotes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,...,genres_Horror,genres_Music,genres_Musical,genres_Mystery,genres_Romance,genres_Sci-Fi,genres_Sport,genres_Thriller,genres_War,genres_Western
123,2001,118,76019048.0,6.4,83716,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4286,2006,125,2139115.0,6.5,612,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5041,2001,104,5271666.0,2.3,23457,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5109,2002,132,5227348.0,6.9,6623,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5123,2001,89,41939.0,5.6,4409,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43911,2020,103,7760946.0,7.5,3588,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
43913,2019,74,59794.0,6.7,147,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43914,2021,96,124317.0,7.8,47,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
43915,2019,97,4540085.0,6.9,8,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
43916,2020,92,317907.0,6.4,4632,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df.describe()

,startYear,runtimeMinutes,world_revenue,averageRating,numVotes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,...,genres_Horror,genres_Music,genres_Musical,genres_Mystery,genres_Romance,genres_Sci-Fi,genres_Sport,genres_Thriller,genres_War,genres_Western
count,32529.000000,32529.000000,3.252900e+04,32529.000000,3.252900e+04,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,...,32529.000000,32529.00000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000
mean,2012.130960,103.379139,1.757425e+07,6.064748,1.857085e+04,0.053460,0.019490,0.049156,0.288696,0.046912,...,0.034738,0.00126,0.001875,0.003720,0.007347,0.000922,0.000461,0.008854,0.000277,0.000092
std,5.588097,19.205527,8.277501e+07,1.143632,7.765203e+04,0.224952,0.138243,0.216197,0.453163,0.211454,...,0.183119,0.03548,0.043264,0.060877,0.085402,0.030355,0.021469,0.093678,0.016632,0.009603
min,2001.000000,44.000000,1.000200e+04,1.000000,5.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2008.000000,90.000000,9.516600e+04,5.400000,2.250000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2012.000000,100.000000,6.301780e+05,6.200000,8.860000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2017.000000,112.000000,4.221733e+06,6.800000,4.741000e+03,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2022.000000,288.000000,2.847380e+09,9.700000,2.555010e+06,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [25]:
df.describe()

,startYear,runtimeMinutes,world_revenue,averageRating,numVotes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,...,genres_Horror,genres_Music,genres_Musical,genres_Mystery,genres_Romance,genres_Sci-Fi,genres_Sport,genres_Thriller,genres_War,genres_Western
count,32529.000000,32529.000000,3.252900e+04,32529.000000,3.252900e+04,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,...,32529.000000,32529.00000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000,32529.000000
mean,2012.130960,103.379139,1.757425e+07,6.064748,1.857085e+04,0.053460,0.019490,0.049156,0.288696,0.046912,...,0.034738,0.00126,0.001875,0.003720,0.007347,0.000922,0.000461,0.008854,0.000277,0.000092
std,5.588097,19.205527,8.277501e+07,1.143632,7.765203e+04,0.224952,0.138243,0.216197,0.453163,0.211454,...,0.183119,0.03548,0.043264,0.060877,0.085402,0.030355,0.021469,0.093678,0.016632,0.009603
min,2001.000000,44.000000,1.000200e+04,1.000000,5.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2008.000000,90.000000,9.516600e+04,5.400000,2.250000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2012.000000,100.000000,6.301780e+05,6.200000,8.860000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2017.000000,112.000000,4.221733e+06,6.800000,4.741000e+03,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2022.000000,288.000000,2.847380e+09,9.700000,2.555010e+06,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [26]:
df.corr()

,startYear,runtimeMinutes,world_revenue,averageRating,numVotes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,...,genres_Horror,genres_Music,genres_Musical,genres_Mystery,genres_Romance,genres_Sci-Fi,genres_Sport,genres_Thriller,genres_War,genres_Western
startYear,1.000000,0.033627,-0.010714,-0.012958,-0.064645,0.018960,0.026662,0.042969,-0.051217,-0.023073,...,0.026919,0.030644,0.011827,0.003900,0.007904,0.007081,0.013847,0.020395,0.007218,-0.011110
runtimeMinutes,0.033627,1.000000,0.149497,0.165920,0.171226,-0.081201,-0.127421,0.056209,-0.064862,0.044266,...,-0.087951,0.033812,0.012538,0.008339,0.021337,-0.009723,0.013071,-0.017484,-0.000136,-0.009691
world_revenue,-0.010714,0.149497,1.000000,0.104917,0.714805,0.124614,-0.016294,-0.014496,-0.056878,-0.015779,...,-0.010713,-0.006286,-0.008881,-0.003084,-0.014185,-0.003229,-0.004336,-0.017156,-0.001954,-0.002029
averageRating,-0.012958,0.165920,0.104917,1.000000,0.185304,-0.033567,0.005629,0.147424,-0.180176,0.029188,...,-0.188764,0.035341,0.007115,-0.016442,-0.020043,-0.017838,-0.005473,-0.044406,-0.011286,-0.010061
numVotes,-0.064645,0.171226,0.714805,0.185304,1.000000,0.055404,-0.023234,0.016406,-0.061367,0.016194,...,0.002108,-0.008140,-0.010151,0.003683,-0.018461,0.004747,-0.004997,-0.019961,-0.003943,-0.002265
genres_Adventure,0.018960,-0.081201,0.124614,-0.033567,0.055404,1.000000,-0.033506,-0.054036,-0.151404,-0.052725,...,-0.045084,-0.008443,-0.010301,-0.014522,-0.020446,-0.007221,-0.005105,-0.022461,-0.003954,-0.002282
genres_Animation,0.026662,-0.127421,-0.016294,0.005629,-0.023234,-0.033506,1.000000,-0.032057,-0.089821,-0.031279,...,-0.026746,-0.005009,-0.006111,-0.008615,-0.012130,-0.004284,-0.003028,-0.013325,-0.002345,-0.001354
genres_Biography,0.042969,0.056209,-0.014496,0.147424,0.016406,-0.054036,-0.032057,1.000000,-0.144853,-0.050444,...,-0.043134,-0.008077,-0.009855,-0.013893,-0.019561,-0.006908,-0.004884,-0.021489,-0.003783,-0.002184
genres_Comedy,-0.051217,-0.064862,-0.056878,-0.180176,-0.061367,-0.151404,-0.089821,-0.144853,1.000000,-0.141341,...,-0.120858,-0.022632,-0.027614,-0.038928,-0.054810,-0.019356,-0.013684,-0.060212,-0.010598,-0.006118
genres_Crime,-0.023073,0.044266,-0.015779,0.029188,0.016194,-0.052725,-0.031279,-0.050444,-0.141341,1.000000,...,-0.042088,-0.007881,-0.009616,-0.013556,-0.019087,-0.006741,-0.004765,-0.020969,-0.003691,-0.002131
genres_Documentary,0.020981,-0.149678,-0.055535,0.266913,-0.061999,-0.067014,-0.039756,-0.064115,-0.179645,-0.062560,...,-0.053494,-0.010017,-0.012222,-0.017230,-0.024260,-0.008567,-0.006057,-0.026651,-0.004691,-0.002708
genres_Drama,-0.029995,0.083626,-0.081347,0.112163,-0.060211,-0.139985,-0.083046,-0.133928,-0.375259,-0.130681,...,-0.111743,-0.020925,-0.025531,-0.035992,-0.050676,-0.017896,-0.012652,-0.055671,-0.009799,-0.005657
genres_Family,0.009512,-0.070309,-0.016934,-0.020302,-0.020476,-0.020746,-0.012307,-0.019848,-0.055613,-0.019367,...,-0.016560,-0.003101,-0.003784,-0.005334,-0.007510,-0.002652,-0.001875,-0.008250,-0.001452,-0.000838
genres_Fantasy,0.005798,-0.011009,-0.004361,-0.034151,-0.003914,-0.013906,-0.008250,-0.013305,-0.037279,-0.012982,...,-0.011101,-0.002079,-0.002536,-0.003575,-0.005034,-0.001778,-0.001257,-0.005530,-0.000973,-0.000562
genres_Film-Noir,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
genres_History,0.007414,0.020118,-0.006059,-0.007405,-0.007513,-0.007687,-0.004561,-0.007355,-0.020607,-0.007176,...,-0.006136,-0.001149,-0.001402,-0.001977,-0.002783,-0.000983,-0.000695,-0.003057,-0.000538,-0.000311
genres_Horror,0.026919,-0.087951,-0.010713,-0.188764,0.002108,-0.045084,-0.026746,-0.043134,-0.120858,-0.042088,...,1.000000,-0.006739,-0.008223,-0.011592,-0.016321,-0.005764,-0.004075,-0.017930,-0.003156,-0.001822
genres_Music,0.030644,0.033812,-0.006286,0.035341,-0.008140,-0.008443,-0.005009,-0.008077,-0.022632,-0.007881,...,-0.006739,1.000000,-0.001540,-0.002171,-0.003056,-0.001079,-0.000763,-0.003358,-0.000591,-0.000341
genres_Musical,0.011827,0.012538,-0.008881,0.007115,-0.010151,-0.010301,-0.006111,-0.009855,-0.027614,-0.009616,...,-0.008223,-0.001540,1.000000,-0.002649,-0.003729,-0.001317,-0.000931,-0.004097,-0.000721,-0.000416
genres_Mystery,0.003900,0.008339,-0.003084,-0.016442,0.003683,-0.014522,-0.008615,-0.013893,-0.038928,-0.013556,...,-0.011592,-0.002171,-0.002649,1.000000,-0.005257,-0.001856,-0.001312,-0.005775,-0.001017,-0.000587
genres_Romance,0.007904,0.021337,-0.014185,-0.020043,-0.018461,-0.020446,-0.012130,-0.019561,-0.054810,-0.019087,...,-0.016321,-0.003056,-0.003729,-0.005257,1.000000,-0.002614,-0.001848,-0.008131,-0.001431,-0.000826
genres_Sci-Fi,0.007081,-0.009723,-0.003229,-0.017838,0.004747,-0.007221,-0.004284,-0.006908,-0.019356,-0.006741,...,-0.005764,-0.001079,-0.001317,-0.001856,-0.002614,1.000000,-0.000653,-0.002872,-0.000505,-0.000292
genres_Sport,0.013847,0.013071,-0.004336,-0.005473,-0.004997,-0.005105,-0.003028,-0.004884,-0.013684,-0.004765,...,-0.004075,-0.000763,-0.000931,-0.001312,-0.001848,-0.000653,1.000000,-0.002030,-0.000357,-0.000206
genres_Thriller,0.020395,-0.017484,-0.017156,-0.044406,-0.019961,-0.022461,-0.013325,-0.021489,-0.060212,-0.020969,...,-0.017930,-0.003358,-0.004097,-0.005775,-0.008131,-0.002872,-0.002030,1.000000,-0.001572,-0.000908
genres_War,0.007218,-0.000136,-0.001954,-0.011286,-0.003943,-0.003954,-0.002345,-0.003783,-0.010598,-0.003691,...,-0.003156,-0.000591,-0.000721,-0.001017,-0.001431,-0.000505,-0.000357,-0.001572,1.000000,-0.000160
genres_Western,-0.011110,-0.009691,-0.002029,-0.010061,-0.002265,-0.002282,-0.001354,-0.002184,-0.006118,-0.002131,...,-0.001822,-0.000341,-0.000416,-0.000587,-0.000826,-0.000292,-0.000206,-0.000908,-0.000160,1.000000

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X = df.drop(['world_revenue'], axis=1).values
y = df.world_revenue.values

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [30]:
X_train.shape

(26023, 25)

In [31]:
y_train.shape

(26023,)

In [32]:
# pip install xgboost

In [33]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
import numpy as np

In [34]:
model = RandomForestRegressor(max_features= 'auto',min_samples_split=6,min_impurity_decrease=0.25,min_samples_leaf=4,n_jobs=-1,random_state=42)

In [35]:
model.fit(X_train, y_train)

RandomForestRegressor(min_impurity_decrease=0.25, min_samples_leaf=4,
                      min_samples_split=6, n_jobs=-1, random_state=42)

In [36]:
round(model.score(X_train, y_train), 2) * 100

82.0

In [37]:
mean_squared_log_error(model.predict(X_train), y_train)**0.5

2.1186887481838674

In [38]:
round(model.score(X_test, y_test), 2) * 100

65.0

In [39]:
mean_squared_log_error(model.predict(X_test), y_test)**0.5

2.403702620113579

In [40]:
mean_squared_error(model.predict(X_test),y_test)**0.5

50669763.590016484

__Tuning__

In [41]:
from sklearn.model_selection import cross_val_score

In [42]:
model = RandomForestRegressor()
cv_result = cross_val_score(model, X, y, cv=10,n_jobs=-1)
cv_result

array([ 0.75941032,  0.68524238,  0.64662535,  0.63910589,  0.7185926 ,
        0.71708432,  0.58108137,  0.56550063,  0.5056001 , -0.05097041])

In [49]:
from xgboost import XGBRFRegressor

In [50]:
xgb = XGBRFRegressor()

In [51]:
xgb.fit(X_train, y_train)

XGBRFRegressor(base_score=0.5, booster='gbtree', callbacks=None,
               colsample_bylevel=1, colsample_bytree=1,
               early_stopping_rounds=None, enable_categorical=False,
               eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
               importance_type=None, interaction_constraints='', max_bin=256,
               max_cat_to_onehot=4, max_delta_step=0, max_depth=6, max_leaves=0,
               min_child_weight=1, missing=nan, monotone_constraints='()',
               n_estimators=100, n_jobs=0, num_parallel_tree=100,
               objective='reg:squarederror', predictor='auto', random_state=0,
               reg_alpha=0, sampling_method='uniform', scale_pos_weight=1, ...)

In [52]:
xgb.score(X_train, y_train)

0.7907231609057696

In [53]:
xgb.score(X_test, y_test)

0.6157310935695236

In [55]:
model = XGBRFRegressor()
cv_result = cross_val_score(model, X, y, cv=10,n_jobs=-1)
cv_result

array([0.75050943, 0.65352051, 0.61283153, 0.66293201, 0.70130829,
       0.71571364, 0.56210003, 0.5589578 , 0.50477065, 0.02304283])